Veoss 979
hmrc/one-stop-shop-registration-frontend pull request #146
Opened 2022-04-26 09:38 UTC by oliwiaKot

2022-04-26 09:48 UTC, oliwiaKot commented
retest this please

2022-04-26 09:55 UTC, oliwiaKot commented
retest this please

2022-04-26 10:09 UTC, oliwiaKot commented
retest this please

2022-04-27 09:21 UTC, DevAndyroo requested changes

2022-04-27 09:21 UTC, DevAndyroo commented on app/models/domain/EuTaxRegistration.scala
> +                                    sellsGoods: Option[Boolean]
I think this should be sendsGoods

2022-04-27 09:48 UTC, oliwiaKot commented on app/models/domain/EuTaxRegistration.scala
> +                                    sellsGoods: Option[Boolean]
oh yes! thanks, just renamed it

2022-04-27 10:10 UTC, oliwiaKot commented
retest this please

2022-04-27 10:51 UTC, DevAndyroo approved these changes

2022-04-27 12:10 UTC, merged